//! This crate is an example for the [soa_derive] crate functionalities. All
//! the code is generated by a single file:
//!
//! ```no_run
//! #[macro_use]
//! extern crate soa_derive;
//!
//! /// A basic Particle type
//! #[derive(Debug, PartialEq, StructOfArray)]
//! #[soa_derive = "Debug, PartialEq"]
//! pub struct Particle {
//!     pub x: f64,
//!     pub y: f64,
//!     pub z: f64,
//!     pub mass: f64,
//!     pub name: String,
//! }
//! ```
//!
//! [soa_derive]: https://github.com/lumol-org/soa-derive/

#[macro_use]
extern crate soa_derive;

/// A basic Particle type
#[derive(Debug, PartialEq, StructOfArray)]
#[soa_derive = "Debug, PartialEq"]
pub struct Particle {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub mass: f64,
    pub name: String,
}
