//! This crate is an example for the [soa_derive] crate functionalities. All
//! the code is generated by a single file:
//!
//! ```no_run
//! #[macro_use]
//! extern crate soa_derive;
//! # fn main() {
//!
//! /// A basic Particle type
//! #[derive(Debug, PartialEq, StructOfArray)]
//! #[soa_derive = "Debug, PartialEq"]
//! pub struct Particle {
//!     /// The x field
//!     #[soa_derive(zip)]
//!     pub x: f64,
//!     /// The y field
//!     #[soa_derive(zip)]
//!     pub y: f64,
//!     /// The z field
//!     #[soa_derive(zip)]
//!     pub z: f64,
//!     /// The mass field
//!     #[soa_derive(zip)]
//!     pub mass: f64,
//!     /// The name field
//!     pub name: String,
//! }
//! # }
//! ```
//!
//! [soa_derive]: https://github.com/lumol-org/soa-derive/

#![deny(missing_docs)]

#[macro_use]
extern crate soa_derive;

/// A basic Particle type
#[derive(Debug, PartialEq, StructOfArray)]
#[soa_derive = "Debug, PartialEq"]
pub struct Particle {
    /// The x field
    #[soa_derive(zip)]
    pub x: f64,
    /// The y field
    #[soa_derive(zip)]
    pub y: f64,
    /// The z field
    #[soa_derive(zip)]
    pub z: f64,
    /// The mass field
    #[soa_derive(zip)]
    pub mass: f64,
    /// The name field
    pub name: String,
}
