sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
    - cd $TRAVIS_BUILD_DIR
    - cargo test
    - cargo test --release
    - cargo bench --no-run
    # Testing and documenting the example
    - rm -rf target/doc
    - cd example
    - cargo doc --no-deps
    - cd $TRAVIS_BUILD_DIR
    - cp example/index.html target/doc/

cache:
  cargo: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: target/doc
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION == stable
